=== Lazenn24/lenguajeDeMarcas/libros/libros.dtd
<!ELEMENT libros (libro, libro)>
<!ELEMENT libro (titulo+, autor, anyoedicion, numpaginas, lengua)>
<!ATTLIST libro isbn CDATA #REQUIRED>
<!ATTLIST libro numcopia CDATA #REQUIRED >
<!ELEMENT titulo EMPTY>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anyoedicion (#PCDATA)>
<!ELEMENT numpaginas (#PCDATA)>
<!ELEMENT lengua (espaÃ±ol|ingles|frances|aleman|EMPTY)>

=== Lazenn24/lenguajeDeMarcas/libros/libros.xml
<?xml version='1.0' ?>
<!DOCTYPE libros SYSTEM "/home/horabaixa/LenguajeDeMarcas/libros/libros.dtd">

<libros>

	<libro isbn= "" numcopia= "">
		<titulo></titulo>
		<titulo></titulo>
		<autor></autor>
		<anyoedicion></anyoedicion>
		<numpaginas></numpaginas>
		<lengua></lengua>
	</libro>
	
	<libro isbn= "" numcopia= "">
		<titulo></titulo>
		<titulo></titulo>	
		<autor></autor>
		<anyoedicion></anyoedicion>
		<numpaginas></numpaginas>
		<lengua></lengua>
	</libro>	
	
</libros>
